using M365_HelpDesk_Administration_Simulator.Forms_Folder;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace M365_HelpDesk_Administration_Simulator
{
    // Main WinForms dashboard for the Service Desk simulator.
    // This form coordinates the fake tenant data, menu actions, user/device/group views,
    // ticket queue, checklist auto-completion, and ticket validation.
    public partial class Form1 : Form
    {
        // In-memory fake tenant data used by the simulator.
        public Storage.FakeDataStore _store;

        // The ticket currently shown in the Ticket Scenario panel.
        private Models.TicketScenario _currentTicket;

        // Shuffled queue of ticket scenarios loaded from JSON.
        private Services.TicketQueueService _ticketQueueService;

        // Prevents the "ticket ready" popup from showing repeatedly for the same ticket.
        private bool _currentTicketReadyToComplete;

        // Used so validation/checklists only count actions performed after this ticket loaded.
        private DateTime _currentTicketLoadedAt;

        // Prevents selection-change events from updating tickets while a ticket is being loaded.
        private bool _isLoadingTicket;

        // Initializes fake data, loads ticket scenarios, populates the dashboard, and starts the first ticket.
        public Form1()
        {
            InitializeComponent();

            _store = Services.SeedDataService.CreateSeedData();
            _ticketQueueService = new Services.TicketQueueService();

            var scenarios = Services.TicketScenarioService.LoadScenariosFromJson();
            _ticketQueueService.LoadQueue(scenarios);

            LoadUsersGrid();
            LoadAuditGrid();
            LoadGroupsComboBox();
            LoadDevicesComboBox();
            DisplaySelectedUser();
            LoadNextTicketFromQueue();
        }

        // Reserved WinForms load event. Currently unused because startup initialization happens in the constructor.
        private void Form1_Load(object sender, EventArgs e)
        {

        }

        // Refreshes the user grid from the current fake data store and reapplies grid formatting.
        private void LoadUsersGrid()
        {
            usersGridView.DataSource = null;
            usersGridView.DataSource = _store.Users;

            FormatUsersGrid();
        }

        // Refreshes the audit log grid, newest entries first, and hides internal identifier columns.
        private void LoadAuditGrid()
        {
            auditGridView.AutoGenerateColumns = true;
            auditGridView.DataSource = null;
            auditGridView.DataSource = _store.AuditEntries
                .OrderByDescending(a => a.Timestamp)
                .ToList();

            if (auditGridView.Columns["Id"] != null)
                auditGridView.Columns["Id"].Visible = false;

            auditGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            auditGridView.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            auditGridView.MultiSelect = false;
            auditGridView.ReadOnly = true;
        }

        // Dequeues and displays the next ticket scenario. If the queue is empty, clears the ticket panel.
        private void LoadNextTicketFromQueue()
        {
            var nextTicket = _ticketQueueService.GetNextTicket();

            if (nextTicket == null)
            {
                ticketTitleLabel.Text = "No tickets remaining";
                ticketDescriptionTextBox.Text = "The ticket queue is empty.";
                expectedActionsCheckedListBox.Items.Clear();

                _currentTicket = null;
                _currentTicketReadyToComplete = false;

                MessageBox.Show("All tickets are complete. Queue empty.");
                return;
            }

            _currentTicketReadyToComplete = false;
            _currentTicketLoadedAt = DateTime.Now;

            _isLoadingTicket = true;
            DisplayTicket(nextTicket);
            _isLoadingTicket = false;
        }

        // Unused label click event generated by the WinForms designer.
        private void label6_Click(object sender, EventArgs e)
        {

        }

        // Filters the user grid by name, email, department, status, or role using the search box text.
        private void SearchUsers()
        {
            string search = userSearchTextBox.Text.Trim().ToLower();

            if (string.IsNullOrWhiteSpace(search))
            {
                LoadUsersGrid();
                SelectFirstUserRowIfAvailable();
                return;
            }

            var filteredUsers = _store.Users
                .Where(user =>
                    user.FirstName.ToLower().Contains(search) ||
                    user.LastName.ToLower().Contains(search) ||
                    user.DisplayName.ToLower().Contains(search) ||
                    user.Email.ToLower().Contains(search) ||
                    user.Department.ToLower().Contains(search) ||
                    user.Status.ToString().ToLower().Contains(search) ||
                    user.Role.ToString().ToLower().Contains(search))
                .ToList();

            usersGridView.DataSource = null;
            usersGridView.DataSource = filteredUsers;

            FormatUsersGrid();
            SelectFirstUserRowIfAvailable();
        }

        // Returns the UserAccount bound to the currently selected user grid row.
        private Models.UserAccount GetSelectedUser()
        {
            if (usersGridView.CurrentRow == null)
                return null;

            return usersGridView.CurrentRow.DataBoundItem as Models.UserAccount;
        }

        // Returns the selected assigned device if one exists; otherwise falls back to the available-device combo box.
        private Models.Device GetSelectedDevice()
        {
            var assignedDevice = GetSelectedAssignedDevice();

            if (assignedDevice != null)
                return assignedDevice;

            return devicesComboBox.SelectedItem as Models.Device;
        }

        // Returns the Device object selected in the selected user's assigned-devices list.
        private Models.Device GetSelectedAssignedDevice()
        {
            return userDevicesListBox.SelectedItem as Models.Device;
        }

        // Finds the specific device named by the current ticket's RequiredDeviceName field.
        private Models.Device GetRequiredTicketDevice()
        {
            if (_currentTicket == null || string.IsNullOrWhiteSpace(_currentTicket.RequiredDeviceName))
                return null;

            return _store.Devices.FirstOrDefault(device =>
                device.DeviceName.Equals(_currentTicket.RequiredDeviceName, StringComparison.OrdinalIgnoreCase));
        }

        // Loads the current ticket title, description, and expected action checklist into the ticket panel.
        private void DisplayTicket(Models.TicketScenario ticket)
        {
            _currentTicket = ticket;

            ticketTitleLabel.Text = ticket.Title;
            ticketDescriptionTextBox.Text = ticket.Description;

            expectedActionsCheckedListBox.Items.Clear();

            foreach (var action in ticket.ExpectedActions)
            {
                expectedActionsCheckedListBox.Items.Add(action, false);
            }
        }

        // Refreshes the selected-user detail panel, mailbox status, group list, assigned devices, and device health view.
        private void DisplaySelectedUser()
        {
            var user = GetSelectedUser();

            userGroupsListBox.Items.Clear();
            userDevicesListBox.Items.Clear();

            if (user == null)
            {
                selectedNameLabel.Text = "-";
                selectedEmailLabel.Text = "-";
                selectedDepartmentLabel.Text = "-";
                selectedStatusLabel.Text = "-";
                selectedRoleLabel.Text = "-";
                mailLicenseLabel.Text = "-";
                mailboxStatusLabel.Text = "-";
                mailboxFullLabel.Text = "-";
                forwardingStatusLabel.Text = "-";
                forwardingAddressLabel.Text = "-";
                return;
            }

            selectedNameLabel.Text = user.DisplayName;
            selectedEmailLabel.Text = user.Email;
            selectedDepartmentLabel.Text = user.Department;
            selectedStatusLabel.Text = user.Status.ToString();
            selectedRoleLabel.Text = user.Role.ToString();

            mailLicenseLabel.Text = user.HasMailLicense ? "Yes" : "No";
            mailboxStatusLabel.Text = user.MailboxStatus;
            mailboxFullLabel.Text = user.MailboxFull ? "Yes" : "No";
            forwardingStatusLabel.Text = user.ForwardingEnabled ? "Enabled" : "Disabled";
            forwardingAddressLabel.Text = string.IsNullOrWhiteSpace(user.ForwardingAddress)
                ? "-"
                : user.ForwardingAddress;

            var userGroups = _store.Groups
                .Where(group => user.GroupIds.Contains(group.Id))
                .ToList();

            foreach (var group in userGroups)
            {
                userGroupsListBox.Items.Add(group.Name);
            }

            if (userGroups.Count == 0)
            {
                userGroupsListBox.Items.Add("No groups assigned");
            }

            var userDevices = _store.Devices
       .Where(device => user.DeviceIds.Contains(device.Id))
       .ToList();

            foreach (var device in userDevices)
            {
                userDevicesListBox.Items.Add(device);
            }

            if (userDevices.Count == 0)
            {
                userDevicesListBox.Items.Add("No devices assigned");
            }

            if (userDevicesListBox.Items.Count > 0 &&
    userDevicesListBox.Items[0] is Models.Device)
            {
                userDevicesListBox.SelectedIndex = 0;
            }
            DisplaySelectedDeviceHealth();
        }

        // Refreshes the Device Health panel from the currently selected assigned or available device.
        private void DisplaySelectedDeviceHealth()
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                selectedDeviceNameLabel.Text = "-";
                bitLockerStatusLabel.Text = "-";
                windowsUpdateStatusLabel.Text = "-";
                defenderStatusLabel.Text = "-";
                diskSpaceStatusLabel.Text = "-";
                lastCheckInStatusLabel.Text = "-";
                localAdminStatusLabel.Text = "-";
                deviceHealthStatusLabel.Text = "-";
                return;
            }

            selectedDeviceNameLabel.Text = device.DeviceName;
            bitLockerStatusLabel.Text = device.BitLockerEnabled ? "Enabled" : "Disabled";
            windowsUpdateStatusLabel.Text = device.WindowsUpdatePending ? "Pending" : "Current";
            defenderStatusLabel.Text = device.DefenderEnabled ? "Enabled" : "Disabled";
            diskSpaceStatusLabel.Text = $"{device.DiskSpaceFreePercent}% free";
            lastCheckInStatusLabel.Text = $"{device.DaysSinceLastCheckIn} day(s) ago";
            localAdminStatusLabel.Text = device.LocalAdminGranted ? "Granted" : "Not Granted";
            deviceHealthStatusLabel.Text = device.DeviceHealthStatus;
        }

        // Handles user selection changes and updates both the details panel and current ticket progress.
        private void usersGridView_SelectionChanged(object sender, EventArgs e)
        {
            DisplaySelectedUser();

            if (!_isLoadingTicket)
            {
                UpdateTicketProgress();
            }
        }

        // Applies common read-only display settings and hides internal data columns in the user grid.
        private void FormatUsersGrid()
        {
            if (usersGridView.Columns["Id"] != null)
                usersGridView.Columns["Id"].Visible = false;

            if (usersGridView.Columns["GroupIds"] != null)
                usersGridView.Columns["GroupIds"].Visible = false;

            if (usersGridView.Columns["DeviceIds"] != null)
                usersGridView.Columns["DeviceIds"].Visible = false;

            if (usersGridView.Columns["CreatedAt"] != null)
                usersGridView.Columns["CreatedAt"].Visible = false;

            usersGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            usersGridView.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            usersGridView.MultiSelect = false;
            usersGridView.ReadOnly = true;
        }

        // Checks whether a matching audit entry was created after the current ticket loaded, preventing old actions from completing new tickets.
        private bool HasAuditEntrySinceTicketLoaded(string action, string target = null, string notesContains = null)
        {
            return _store.AuditEntries.Any(a =>
                a.Timestamp >= _currentTicketLoadedAt &&
                a.Action == action &&
                (target == null || a.Target == target) &&
                (notesContains == null || a.Notes.Contains(notesContains)));
        }


        // Creates a simple fake temporary password for password-reset simulations.
        private string GenerateTemporaryPassword()
        {
            Random random = new Random();

            int number = random.Next(1000, 9999);

            return $"Temp-{number}!";
        }


        // Refreshes the group combo box from the current fake group list.
        private void LoadGroupsComboBox()
        {
            groupsComboBox.DataSource = null;
            groupsComboBox.DataSource = _store.Groups;
            groupsComboBox.DisplayMember = "DisplayLabel";
            groupsComboBox.ValueMember = "Id";
        }
        // Refreshes the available-device combo box with active, unassigned devices only.
        private void LoadDevicesComboBox()
        {
            var availableDevices = _store.Devices
       .Where(device =>
           device.Status == Models.DeviceStatus.Active &&
           device.AssignedUserId == null)
       .ToList();

            devicesComboBox.DataSource = null;
            devicesComboBox.DataSource = availableDevices;
            devicesComboBox.DisplayMember = "DisplayLabel";
            devicesComboBox.ValueMember = "Id";

            DisplaySelectedDeviceHealth();
        }

        // Opens the Add User dialog, adds the created user to the fake store, writes an audit entry, and refreshes the dashboard.
        private void OpenAddUserForm()
        {
            using (var form = new AddUserForm(_store))
            {
                DialogResult result = form.ShowDialog();

                if (result != DialogResult.OK || form.CreatedUser == null)
                    return;

                _store.Users.Add(form.CreatedUser);

                AddAuditEntry(
                    "Created User",
                    form.CreatedUser.DisplayName,
                    $"{form.CreatedUser.Email} was created in the simulator."
                );

                LoadUsersGrid();
                DisplaySelectedUser();
                UpdateTicketProgress();

                MessageBox.Show($"{form.CreatedUser.DisplayName} has been created.");
            }
        }

        // Opens the Add Device dialog, adds the created device to the fake store, writes an audit entry, and refreshes device views.
        private void OpenAddDeviceForm()
        {
            using (var form = new AddDeviceForm(_store))
            {
                DialogResult result = form.ShowDialog();

                if (result != DialogResult.OK || form.CreatedDevice == null)
                    return;

                _store.Devices.Add(form.CreatedDevice);

                AddAuditEntry(
                    "Created Device",
                    form.CreatedDevice.DeviceName,
                    $"{form.CreatedDevice.DeviceName} was added to device inventory as {form.CreatedDevice.Status}."
                );

                LoadDevicesComboBox();
                DisplaySelectedUser();
                UpdateTicketProgress();

                MessageBox.Show($"{form.CreatedDevice.DeviceName} has been added to device inventory.");
            }
        }

        // Opens the Add Group dialog, adds the created group to the fake store, writes an audit entry, and refreshes group views.
        private void OpenAddGroupForm()
        {
            using (var form = new AddGroupForm(_store))
            {
                DialogResult result = form.ShowDialog();

                if (result != DialogResult.OK || form.CreatedGroup == null)
                    return;

                _store.Groups.Add(form.CreatedGroup);

                AddAuditEntry(
                    "Created Group",
                    form.CreatedGroup.Name,
                    $"{form.CreatedGroup.Name} was created. {form.CreatedGroup.Description}"
                );

                LoadGroupsComboBox();
                DisplaySelectedUser();
                UpdateTicketProgress();

                MessageBox.Show($"{form.CreatedGroup.Name} has been created.");
            }
        }


        // Creates a standard audit log entry and refreshes the audit grid.
        private void AddAuditEntry(string action, string target, string notes)
        {
            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = action,
                Target = target,
                Notes = notes
            });

            LoadAuditGrid();
        }

        // Unused GroupBox enter event generated by the WinForms designer.
        private void ticketGroupBox_Enter(object sender, EventArgs e)
        {

        }

        // Routes the current ticket to the correct checklist updater based on scenario type.
        private void UpdateTicketProgress()
        {
            if (_currentTicket == null)
                return;

            switch (_currentTicket.ScenarioType)
            {
                case Models.TicketScenarioType.NewHireOnboarding:
                    UpdateNewHireOnboardingChecklist();
                    break;

                case Models.TicketScenarioType.PasswordReset:
                    UpdatePasswordResetChecklist();
                    break;

                case Models.TicketScenarioType.SalesDriveAccess:
                    UpdateSalesDriveAccessChecklist();
                    break;

                case Models.TicketScenarioType.LostLaptop:
                    UpdateLostLaptopChecklist();
                    break;

                case Models.TicketScenarioType.EmployeeOffboarding:
                    UpdateEmployeeOffboardingChecklist();
                    break;

                case Models.TicketScenarioType.ReplacementLaptop:
                    UpdateReplacementLaptopChecklist();
                    break;

                case Models.TicketScenarioType.EmailTroubleshooting:
                    UpdateEmailTroubleshootingChecklist();
                    break;

                case Models.TicketScenarioType.DeviceHealthTroubleshooting:
                    UpdateDeviceHealthTroubleshootingChecklist();
                    break;
            }

            CheckIfTicketReadyToComplete();
        }

        // Auto-checks onboarding checklist items based on whether the new user, group access, role, device, and audit entry exist.
        private void UpdateNewHireOnboardingChecklist()
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email.Equals(_currentTicket.TargetUserEmail, StringComparison.OrdinalIgnoreCase));

            bool userExists = user != null;

            SetChecklistItemChecked(
                $"Create account for {_currentTicket.RequiredFirstName} {_currentTicket.RequiredLastName}",
                userExists
            );

            if (!userExists)
                return;

            var selectedUser = GetSelectedUser();

            SetChecklistItemChecked(
                $"Find and select {user.DisplayName}",
                selectedUser != null && selectedUser.Email.Equals(user.Email, StringComparison.OrdinalIgnoreCase)
            );

            SetChecklistItemChecked(
                $"Confirm {user.FirstName}'s account is Active",
                user.Status == Models.UserStatus.Active
            );

            SetChecklistItemChecked(
                $"Assign {user.FirstName} the {_currentTicket.RequiredRole} role",
                user.Role == _currentTicket.RequiredRole
            );

            var requiredGroup = _store.Groups
                .FirstOrDefault(g => g.Name.Equals(_currentTicket.RequiredGroupName, StringComparison.OrdinalIgnoreCase));

            bool hasRequiredGroup =
                requiredGroup != null &&
                user.GroupIds.Contains(requiredGroup.Id);

            SetChecklistItemChecked(
                $"Add {user.FirstName} to {_currentTicket.RequiredGroupName}",
                hasRequiredGroup
            );

            bool hasActiveAssignedDevice = _store.Devices.Any(d =>
                d.AssignedUserId == user.Id &&
                d.Status == Models.DeviceStatus.Active);

            SetChecklistItemChecked(
                $"Assign an active device to {user.FirstName}",
                hasActiveAssignedDevice
            );

            bool hasCreatedUserAudit = _store.AuditEntries.Any(a =>
                a.Action == "Created User" &&
                a.Target == user.DisplayName);

            SetChecklistItemChecked(
                "Verify user creation appears in the audit log",
                hasCreatedUserAudit
            );
        }

        // Routes ticket completion validation to the correct validator based on scenario type.
        private bool ValidateCurrentTicket(out string message)
        {
            message = "";

            if (_currentTicket == null)
            {
                message = "Load a ticket first.";
                return false;
            }

            switch (_currentTicket.ScenarioType)
            {
                case Models.TicketScenarioType.NewHireOnboarding:
                    return ValidateNewHireOnboardingTicket(out message);

                case Models.TicketScenarioType.SalesDriveAccess:
                    return ValidateSalesDriveAccessTicket(out message);

                case Models.TicketScenarioType.EmployeeOffboarding:
                    return ValidateEmployeeOffboardingTicket(out message);

                case Models.TicketScenarioType.ReplacementLaptop:
                    return ValidateReplacementLaptopTicket(out message);

                case Models.TicketScenarioType.LostLaptop:
                    return ValidateLostLaptopTicket(out message);

                case Models.TicketScenarioType.PasswordReset:
                    return ValidatePasswordResetTicket(out message);

                case Models.TicketScenarioType.EmailTroubleshooting:
                    return ValidateEmailTroubleshootingTicket(out message);

                case Models.TicketScenarioType.DeviceHealthTroubleshooting:
                    return ValidateDeviceHealthTroubleshootingTicket(out message);

                default:
                    message = "Unknown ticket type.";
                    return false;
            }
        }

        // Validates that the target user's password reset was performed and audited.
        private bool ValidatePasswordResetTicket(out string message)
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
            {
                message = "Target user was not found.";
                return false;
            }

            if (user.Status == Models.UserStatus.SoftDeleted)
            {
                message = $"{user.DisplayName} is soft-deleted. Password reset should not be completed for this account.";
                return false;
            }

            bool hasPasswordResetAudit = _store.AuditEntries.Any(a =>
                a.Action == "Reset Password" &&
                a.Target == user.DisplayName);

            if (!hasPasswordResetAudit)
            {
                message = $"No password reset audit entry found for {user.DisplayName}.";
                return false;
            }

            message = "Password reset ticket completed successfully.";
            return true;
        }

        // Validates that the target user is active and has Sales shared-drive access.
        private bool ValidateSalesDriveAccessTicket(out string message)
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
            {
                message = "Target user was not found.";
                return false;
            }

            if (user.Status != Models.UserStatus.Active)
            {
                message = $"{user.DisplayName}'s account is not active.";
                return false;
            }

            var salesGroup = _store.Groups
                .FirstOrDefault(g => g.Name == "Sales-SharedDrive-Access");

            if (salesGroup == null)
            {
                message = "Sales-SharedDrive-Access group was not found.";
                return false;
            }

            if (!user.GroupIds.Contains(salesGroup.Id))
            {
                message = $"{user.DisplayName} is not a member of Sales-SharedDrive-Access.";
                return false;
            }

            message = "Sales drive access ticket completed successfully.";
            return true;
        }

        // Validates lost-laptop remediation: device unassigned/lost, password reset performed, and audit entries exist.
        private bool ValidateLostLaptopTicket(out string message)
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
            {
                message = "Target user was not found.";
                return false;
            }

            bool hasAssignedDevices = _store.Devices.Any(d => d.AssignedUserId == user.Id);

            if (hasAssignedDevices)
            {
                message = $"{user.DisplayName} still has assigned devices.";
                return false;
            }

            bool hasLostDeviceAudit = _store.AuditEntries.Any(a =>
                a.Action == "Marked Device Lost");

            if (!hasLostDeviceAudit)
            {
                message = "No lost device audit entry was found.";
                return false;
            }

            bool hasPasswordResetAudit = _store.AuditEntries.Any(a =>
                a.Action == "Reset Password" &&
                a.Target == user.DisplayName);

            if (!hasPasswordResetAudit)
            {
                message = $"No password reset audit entry found for {user.DisplayName}.";
                return false;
            }

            message = "Lost laptop ticket completed successfully.";
            return true;
        }

        // Validates offboarding: account disabled or soft-deleted, group access removed, and devices unassigned.
        private bool ValidateEmployeeOffboardingTicket(out string message)
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
            {
                message = "Target user was not found.";
                return false;
            }

            if (user.Status != Models.UserStatus.Disabled &&
                user.Status != Models.UserStatus.SoftDeleted)
            {
                message = $"{user.DisplayName}'s account should be disabled or soft-deleted.";
                return false;
            }

            if (user.GroupIds.Count > 0)
            {
                message = $"{user.DisplayName} still has group access assigned.";
                return false;
            }

            bool hasAssignedDevices = _store.Devices.Any(d => d.AssignedUserId == user.Id);

            if (hasAssignedDevices)
            {
                message = $"{user.DisplayName} still has assigned devices.";
                return false;
            }

            message = "Employee offboarding ticket completed successfully.";
            return true;
        }

        // Validates that the target user has an active assigned device.
        private bool ValidateReplacementLaptopTicket(out string message)
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
            {
                message = "Target user was not found.";
                return false;
            }

            if (user.Status != Models.UserStatus.Active)
            {
                message = $"{user.DisplayName}'s account must be active.";
                return false;
            }

            bool hasActiveAssignedDevice = _store.Devices.Any(d =>
                d.AssignedUserId == user.Id &&
                d.Status == Models.DeviceStatus.Active);

            if (!hasActiveAssignedDevice)
            {
                message = $"{user.DisplayName} does not have an active assigned device.";
                return false;
            }

            message = "Replacement laptop ticket completed successfully.";
            return true;
        }

        // Validates new-hire setup: user exists, status, department, role, required group, assigned device, and audit log.
        private bool ValidateNewHireOnboardingTicket(out string message)
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email.Equals(_currentTicket.TargetUserEmail, StringComparison.OrdinalIgnoreCase));

            if (user == null)
            {
                message = $"User {_currentTicket.RequiredFirstName} {_currentTicket.RequiredLastName} has not been created.";
                return false;
            }

            if (user.Status != Models.UserStatus.Active)
            {
                message = $"{user.DisplayName}'s account must be Active.";
                return false;
            }

            if (!user.Department.Equals(_currentTicket.RequiredDepartment, StringComparison.OrdinalIgnoreCase))
            {
                message = $"{user.DisplayName} must be in the {_currentTicket.RequiredDepartment} department.";
                return false;
            }

            if (user.Role != _currentTicket.RequiredRole)
            {
                message = $"{user.DisplayName} must have the {_currentTicket.RequiredRole} role.";
                return false;
            }

            var requiredGroup = _store.Groups
                .FirstOrDefault(g => g.Name.Equals(_currentTicket.RequiredGroupName, StringComparison.OrdinalIgnoreCase));

            if (requiredGroup == null)
            {
                message = $"Required group {_currentTicket.RequiredGroupName} was not found.";
                return false;
            }

            if (!user.GroupIds.Contains(requiredGroup.Id))
            {
                message = $"{user.DisplayName} is not in {_currentTicket.RequiredGroupName}.";
                return false;
            }

            bool hasActiveAssignedDevice = _store.Devices.Any(d =>
                d.AssignedUserId == user.Id &&
                d.Status == Models.DeviceStatus.Active);

            if (!hasActiveAssignedDevice)
            {
                message = $"{user.DisplayName} does not have an active assigned device.";
                return false;
            }

            bool hasCreatedUserAudit = _store.AuditEntries.Any(a =>
                a.Action == "Created User" &&
                a.Target == user.DisplayName);

            if (!hasCreatedUserAudit)
            {
                message = $"No Created User audit entry found for {user.DisplayName}.";
                return false;
            }

            message = "New hire onboarding ticket completed successfully.";
            return true;
        }

        // Validates email troubleshooting actions such as clearing mailbox full, assigning license, disabling forwarding, or unblocking mailbox.
        private bool ValidateEmailTroubleshootingTicket(out string message)
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email.Equals(_currentTicket.TargetUserEmail, StringComparison.OrdinalIgnoreCase));

            if (user == null)
            {
                message = "Target user was not found.";
                return false;
            }

            switch (_currentTicket.RequiredEmailIssue)
            {
                case "MailboxFull":
                    if (user.MailboxFull)
                    {
                        message = $"{user.DisplayName}'s mailbox is still marked full.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Cleared Mailbox Full Warning", user.DisplayName))
                    {
                        message = $"No mailbox full warning clearance audit entry found for {user.DisplayName}.";
                        return false;
                    }

                    break;

                case "MissingMailLicense":
                    if (!user.HasMailLicense)
                    {
                        message = $"{user.DisplayName} still does not have a mail license.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Assigned Mail License", user.DisplayName))
                    {
                        message = $"No mail license assignment audit entry found for {user.DisplayName}.";
                        return false;
                    }

                    break;

                case "ForwardingEnabled":
                    if (user.ForwardingEnabled)
                    {
                        message = $"{user.DisplayName} still has mail forwarding enabled.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Disabled Mail Forwarding", user.DisplayName))
                    {
                        message = $"No disabled forwarding audit entry found for {user.DisplayName}.";
                        return false;
                    }

                    break;

                case "MailboxBlocked":
                    if (user.MailboxBlocked)
                    {
                        message = $"{user.DisplayName}'s mailbox is still blocked.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Unblocked Mailbox", user.DisplayName))
                    {
                        message = $"No mailbox unblock audit entry found for {user.DisplayName}.";
                        return false;
                    }

                    break;

                default:
                    message = "Unknown email troubleshooting issue type.";
                    return false;
            }

            message = "Email troubleshooting ticket completed successfully.";
            return true;
        }

        // Validates device-health remediation such as Windows Update, BitLocker, Defender, disk cleanup, or check-in refresh.
        private bool ValidateDeviceHealthTroubleshootingTicket(out string message)
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email.Equals(_currentTicket.TargetUserEmail, StringComparison.OrdinalIgnoreCase));

            if (user == null)
            {
                message = "Target user was not found.";
                return false;
            }

            var device = GetRequiredTicketDevice();

            if (device == null)
            {
                message = $"Required device {_currentTicket.RequiredDeviceName} was not found.";
                return false;
            }

            if (device.AssignedUserId != user.Id)
            {
                message = $"{device.DeviceName} is not assigned to {user.DisplayName}.";
                return false;
            }

            switch (_currentTicket.RequiredDeviceIssue)
            {
                case "WindowsUpdatePending":
                    if (device.WindowsUpdatePending)
                    {
                        message = $"{device.DeviceName} still has pending Windows updates.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Ran Windows Update", device.DeviceName))
                    {
                        message = $"No Windows Update audit entry found for {device.DeviceName}.";
                        return false;
                    }
                    break;

                case "BitLockerDisabled":
                    if (!device.BitLockerEnabled)
                    {
                        message = $"{device.DeviceName} still does not have BitLocker enabled.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Enabled BitLocker", device.DeviceName))
                    {
                        message = $"No BitLocker audit entry found for {device.DeviceName}.";
                        return false;
                    }
                    break;

                case "DefenderDisabled":
                    if (!device.DefenderEnabled)
                    {
                        message = $"{device.DeviceName} still has Defender disabled.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Enabled Defender", device.DeviceName))
                    {
                        message = $"No Defender audit entry found for {device.DeviceName}.";
                        return false;
                    }
                    break;

                case "LowDiskSpace":
                    if (device.DiskSpaceFreePercent < 15)
                    {
                        message = $"{device.DeviceName} still has low disk space.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Cleared Disk Space", device.DeviceName))
                    {
                        message = $"No disk cleanup audit entry found for {device.DeviceName}.";
                        return false;
                    }
                    break;

                case "CheckInStale":
                    if (device.DaysSinceLastCheckIn > 7)
                    {
                        message = $"{device.DeviceName} still has a stale check-in.";
                        return false;
                    }

                    if (!HasAuditEntrySinceTicketLoaded("Refreshed Device Check-In", device.DeviceName))
                    {
                        message = $"No check-in refresh audit entry found for {device.DeviceName}.";
                        return false;
                    }
                    break;

                default:
                    message = "Unknown device health issue type.";
                    return false;
            }

            message = "Device health troubleshooting ticket completed successfully.";
            return true;
        }

        // Checks or unchecks a ticket checklist item by exact display text.
        private void SetChecklistItemChecked(string expectedText, bool isChecked)
        {
            if (expectedActionsCheckedListBox == null)
                return;

            for (int i = 0; i < expectedActionsCheckedListBox.Items.Count; i++)
            {
                string itemText = expectedActionsCheckedListBox.Items[i]?.ToString();

                if (itemText == expectedText)
                {
                    expectedActionsCheckedListBox.SetItemChecked(i, isChecked);
                    return;
                }
            }
        }

        // Updates password-reset ticket checklist items from selected user and ticket-time audit entries.
        private void UpdatePasswordResetChecklist()
        {
            var user = _store.Users
       .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
                return;

            var selectedUser = GetSelectedUser();

            bool selectedTargetUser =
                selectedUser != null &&
                selectedUser.Email.Equals(user.Email, StringComparison.OrdinalIgnoreCase);

            SetChecklistItemChecked(
                $"Find and select {user.DisplayName}",
                selectedTargetUser
            );

            SetChecklistItemChecked(
                "Confirm account is not soft-deleted",
                selectedTargetUser && user.Status != Models.UserStatus.SoftDeleted
            );

            bool hasPasswordResetAudit = HasAuditEntrySinceTicketLoaded(
                "Reset Password",
                user.DisplayName
            );

            SetChecklistItemChecked(
                $"Reset {user.FirstName}'s password",
                hasPasswordResetAudit
            );

            SetChecklistItemChecked(
                "Verify password reset appears in the audit log",
                hasPasswordResetAudit
            );
        }

        // Updates Sales access checklist items from selected user, group membership, and ticket-time group audit entries.
        private void UpdateSalesDriveAccessChecklist()
        {
            var user = _store.Users
       .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
                return;

            var selectedUser = GetSelectedUser();

            bool selectedTargetUser =
                selectedUser != null &&
                selectedUser.Email.Equals(user.Email, StringComparison.OrdinalIgnoreCase);

            var salesGroup = _store.Groups
                .FirstOrDefault(g => g.Name == "Sales-SharedDrive-Access");

            bool isInSalesGroup =
                salesGroup != null &&
                user.GroupIds.Contains(salesGroup.Id);

            bool addedToGroupDuringThisTicket = HasAuditEntrySinceTicketLoaded(
                "Added User to Group",
                user.DisplayName,
                "Sales-SharedDrive-Access"
            );

            SetChecklistItemChecked(
                $"Find and select {user.DisplayName}",
                selectedTargetUser
            );

            SetChecklistItemChecked(
                "Confirm account status is Active",
                selectedTargetUser && user.Status == Models.UserStatus.Active
            );

            SetChecklistItemChecked(
                "Confirm Sales-SharedDrive-Access group membership",
                selectedTargetUser && isInSalesGroup
            );

            SetChecklistItemChecked(
                "Add Sarah to Sales-SharedDrive-Access if missing",
                addedToGroupDuringThisTicket
            );

            SetChecklistItemChecked(
                "Verify the action appears in the audit log",
                addedToGroupDuringThisTicket
            );
        }

        // Updates lost-laptop checklist items from selected user, device assignment state, and ticket-time audit entries.
        private void UpdateLostLaptopChecklist()
        {
            var user = _store.Users
        .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
                return;

            var selectedUser = GetSelectedUser();

            bool selectedTargetUser =
                selectedUser != null &&
                selectedUser.Email.Equals(user.Email, StringComparison.OrdinalIgnoreCase);

            bool hasLostDeviceAudit = _store.AuditEntries.Any(a =>
                a.Timestamp >= _currentTicketLoadedAt &&
                a.Action == "Marked Device Lost");

            bool hasPasswordResetAudit = HasAuditEntrySinceTicketLoaded(
                "Reset Password",
                user.DisplayName
            );

            bool hasNoAssignedDevices = !_store.Devices.Any(d =>
                d.AssignedUserId == user.Id);

            SetChecklistItemChecked(
                $"Find and select {user.DisplayName}",
                selectedTargetUser
            );

            SetChecklistItemChecked(
                $"Mark {user.FirstName}'s assigned laptop as Lost",
                hasLostDeviceAudit
            );

            SetChecklistItemChecked(
                $"Reset {user.FirstName}'s password",
                hasPasswordResetAudit
            );

            SetChecklistItemChecked(
                "Confirm the lost device is no longer assigned",
                hasLostDeviceAudit && hasNoAssignedDevices
            );

            SetChecklistItemChecked(
                "Verify the audit log",
                hasLostDeviceAudit && hasPasswordResetAudit
            );
        }

        // Updates offboarding checklist items from account status, group removal, device removal, and audit entries.
        private void UpdateEmployeeOffboardingChecklist()
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);

            if (user == null)
                return;

            var selectedUser = GetSelectedUser();

            bool accountDisabledOrDeleted =
                user.Status == Models.UserStatus.Disabled ||
                user.Status == Models.UserStatus.SoftDeleted;

            bool hasNoGroups = user.GroupIds.Count == 0;

            bool hasNoAssignedDevices = !_store.Devices.Any(d =>
                d.AssignedUserId == user.Id);

            bool hasDisableAudit = _store.AuditEntries.Any(a =>
                a.Action == "Disabled Account" &&
                a.Target == user.DisplayName);

            bool hasDeviceRetiredAudit = _store.AuditEntries.Any(a =>
                a.Action == "Retired Device");

            SetChecklistItemChecked(
                $"Find and select {user.DisplayName}",
                selectedUser != null && selectedUser.Email == user.Email
            );

            SetChecklistItemChecked(
                $"Disable {user.FirstName}'s account",
                accountDisabledOrDeleted || hasDisableAudit
            );

            SetChecklistItemChecked(
                "Remove unnecessary group access",
                hasNoGroups
            );

            SetChecklistItemChecked(
                $"Retire {user.FirstName}'s assigned laptop",
                hasNoAssignedDevices || hasDeviceRetiredAudit
            );

            SetChecklistItemChecked(
                "Verify all changes appear in the audit log",
                hasDisableAudit || hasDeviceRetiredAudit
            );
        }

        // Updates replacement-laptop checklist items from selected user and active assigned-device state.
        private void UpdateReplacementLaptopChecklist()
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email == _currentTicket.TargetUserEmail);
            if (user == null)
                return;
            var selectedUser = GetSelectedUser();

            bool hasActiveAssignedDevice = _store.Devices.Any(d =>
                d.AssignedUserId == user.Id &&
                d.Status == Models.DeviceStatus.Active);
            SetChecklistItemChecked(
                $"Find and select {user.DisplayName}",
                selectedUser != null && selectedUser.Email == user.Email
            );

            SetChecklistItemChecked(
                "Confirm account status is Active",
                user.Status == Models.UserStatus.Active
            );

            SetChecklistItemChecked(
                "Verify the user has an active assigned device",
                hasActiveAssignedDevice
            );
        }

        // Routes an email troubleshooting ticket to the correct mailbox-specific checklist updater.
        private void UpdateEmailTroubleshootingChecklist()
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email.Equals(_currentTicket.TargetUserEmail, StringComparison.OrdinalIgnoreCase));

            if (user == null)
                return;

            var selectedUser = GetSelectedUser();

            bool selectedTargetUser =
                selectedUser != null &&
                selectedUser.Email.Equals(user.Email, StringComparison.OrdinalIgnoreCase);

            SetChecklistItemChecked(
                $"Find and select {user.DisplayName}",
                selectedTargetUser
            );

            SetChecklistItemChecked(
                "Review mailbox status",
                selectedTargetUser
            );

            switch (_currentTicket.RequiredEmailIssue)
            {
                case "MailboxFull":
                    UpdateMailboxFullChecklist(user);
                    break;

                case "MissingMailLicense":
                    UpdateMissingMailLicenseChecklist(user);
                    break;

                case "ForwardingEnabled":
                    UpdateForwardingChecklist(user);
                    break;

                case "MailboxBlocked":
                    UpdateMailboxBlockedChecklist(user);
                    break;
            }
        }

        // Updates checklist items for clearing a mailbox-full condition.
        private void UpdateMailboxFullChecklist(Models.UserAccount user)
        {
            bool clearedMailboxFull = HasAuditEntrySinceTicketLoaded(
                "Cleared Mailbox Full Warning",
                user.DisplayName
            );

            SetChecklistItemChecked(
                "Clear mailbox full warning",
                clearedMailboxFull
            );

            SetChecklistItemChecked(
                "Verify mailbox status is Healthy",
                clearedMailboxFull && user.MailboxStatus == "Healthy"
            );
        }

        // Updates checklist items for assigning a missing mail license.
        private void UpdateMissingMailLicenseChecklist(Models.UserAccount user)
        {
            bool assignedMailLicense = HasAuditEntrySinceTicketLoaded(
                "Assigned Mail License",
                user.DisplayName
            );

            SetChecklistItemChecked(
                "Assign mail license",
                assignedMailLicense
            );

            SetChecklistItemChecked(
                "Verify mail license is assigned",
                assignedMailLicense && user.HasMailLicense
            );
        }

        // Updates checklist items for disabling suspicious mail forwarding.
        private void UpdateForwardingChecklist(Models.UserAccount user)
        {
            bool disabledForwarding = HasAuditEntrySinceTicketLoaded(
                "Disabled Mail Forwarding",
                user.DisplayName
            );

            SetChecklistItemChecked(
                "Disable suspicious mail forwarding",
                disabledForwarding
            );

            SetChecklistItemChecked(
                "Verify forwarding is disabled",
                disabledForwarding && !user.ForwardingEnabled
            );
        }

        // Updates checklist items for unblocking a blocked mailbox.
        private void UpdateMailboxBlockedChecklist(Models.UserAccount user)
        {
            bool unblockedMailbox = HasAuditEntrySinceTicketLoaded(
                "Unblocked Mailbox",
                user.DisplayName
            );

            SetChecklistItemChecked(
                "Unblock mailbox",
                unblockedMailbox
            );

            SetChecklistItemChecked(
                "Verify mailbox is no longer blocked",
                unblockedMailbox && !user.MailboxBlocked
            );
        }

        // Routes a device-health ticket to the correct device issue checklist updater.
        private void UpdateDeviceHealthTroubleshootingChecklist()
        {
            var user = _store.Users
                .FirstOrDefault(u => u.Email.Equals(_currentTicket.TargetUserEmail, StringComparison.OrdinalIgnoreCase));

            if (user == null)
                return;

            var requiredDevice = GetRequiredTicketDevice();

            if (requiredDevice == null)
                return;

            var selectedUser = GetSelectedUser();
            var selectedDevice = GetSelectedDevice();

            bool selectedTargetUser =
                selectedUser != null &&
                selectedUser.Email.Equals(user.Email, StringComparison.OrdinalIgnoreCase);

            bool selectedRequiredDevice =
                selectedDevice != null &&
                selectedDevice.DeviceName.Equals(requiredDevice.DeviceName, StringComparison.OrdinalIgnoreCase);

            SetChecklistItemChecked(
                $"Find and select {user.DisplayName}",
                selectedTargetUser
            );

            SetChecklistItemChecked(
                "Review assigned device health",
                selectedTargetUser && selectedRequiredDevice
            );

            switch (_currentTicket.RequiredDeviceIssue)
            {
                case "WindowsUpdatePending":
                    UpdateWindowsUpdatePendingChecklist(requiredDevice);
                    break;

                case "BitLockerDisabled":
                    UpdateBitLockerDisabledChecklist(requiredDevice);
                    break;

                case "DefenderDisabled":
                    UpdateDefenderDisabledChecklist(requiredDevice);
                    break;

                case "LowDiskSpace":
                    UpdateLowDiskSpaceChecklist(requiredDevice);
                    break;

                case "CheckInStale":
                    UpdateCheckInStaleChecklist(requiredDevice);
                    break;
            }
        }

        // Updates checklist items for applying pending Windows updates.
        private void UpdateWindowsUpdatePendingChecklist(Models.Device device)
        {
            bool ranWindowsUpdate = HasAuditEntrySinceTicketLoaded(
                "Ran Windows Update",
                device.DeviceName
            );

            SetChecklistItemChecked(
                "Run Windows Update",
                ranWindowsUpdate
            );

            SetChecklistItemChecked(
                "Verify Windows Update status is Current",
                ranWindowsUpdate && !device.WindowsUpdatePending
            );
        }

        // Updates checklist items for enabling BitLocker.
        private void UpdateBitLockerDisabledChecklist(Models.Device device)
        {
            bool enabledBitLocker = HasAuditEntrySinceTicketLoaded(
                "Enabled BitLocker",
                device.DeviceName
            );

            SetChecklistItemChecked(
                "Enable BitLocker",
                enabledBitLocker
            );

            SetChecklistItemChecked(
                "Verify BitLocker is Enabled",
                enabledBitLocker && device.BitLockerEnabled
            );
        }

        // Updates checklist items for enabling Microsoft Defender.
        private void UpdateDefenderDisabledChecklist(Models.Device device)
        {
            bool enabledDefender = HasAuditEntrySinceTicketLoaded(
                "Enabled Defender",
                device.DeviceName
            );

            SetChecklistItemChecked(
                "Enable Defender",
                enabledDefender
            );

            SetChecklistItemChecked(
                "Verify Defender is Enabled",
                enabledDefender && device.DefenderEnabled
            );
        }

        // Updates checklist items for disk cleanup / low disk space remediation.
        private void UpdateLowDiskSpaceChecklist(Models.Device device)
        {
            bool clearedDiskSpace = HasAuditEntrySinceTicketLoaded(
                "Cleared Disk Space",
                device.DeviceName
            );

            SetChecklistItemChecked(
                "Clear Disk Space",
                clearedDiskSpace
            );

            SetChecklistItemChecked(
                "Verify disk space is above 15%",
                clearedDiskSpace && device.DiskSpaceFreePercent >= 15
            );
        }

        // Updates checklist items for refreshing a stale device check-in.
        private void UpdateCheckInStaleChecklist(Models.Device device)
        {
            bool refreshedCheckIn = HasAuditEntrySinceTicketLoaded(
                "Refreshed Device Check-In",
                device.DeviceName
            );

            SetChecklistItemChecked(
                "Refresh Device Check-In",
                refreshedCheckIn
            );

            SetChecklistItemChecked(
                "Verify last check-in is current",
                refreshedCheckIn && device.DaysSinceLastCheckIn == 0
            );
        }

        // Shows a ready-to-complete message once every checklist item is checked.
        private void CheckIfTicketReadyToComplete()
        {
            if (_currentTicket == null)
                return;

            if (_currentTicketReadyToComplete)
                return;

            for (int i = 0; i < expectedActionsCheckedListBox.Items.Count; i++)
            {
                if (!expectedActionsCheckedListBox.GetItemChecked(i))
                    return;
            }

            _currentTicketReadyToComplete = true;

            MessageBox.Show(
                "All expected actions are complete.\n\nYou can now mark this ticket as completed.",
                "Ticket Ready",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information
            );
        }

        // Closes the application from the File menu.
        private void exitToolStripMenuItem_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }

        // Currently resets the active ticket checklist, not the full environment.
        private void resetEnvironmentToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (_currentTicket == null)
            {
                MessageBox.Show("No ticket is currently loaded.");
                return;
            }

            _currentTicketReadyToComplete = false;

            DisplayTicket(_currentTicket);
            UpdateTicketProgress();
        }

        // Enables the selected user account unless it is soft-deleted or already active.
        private void enableUserToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please Find and select a user first.");
                return;
            }

            if (user.Status == Models.UserStatus.SoftDeleted)
            {
                MessageBox.Show("Cannot enable a soft-deleted user. Restore the account first.");
                return;
            }

            if (user.Status == Models.UserStatus.Active)
            {
                MessageBox.Show($"{user.DisplayName}'s account is already active.");
                return;
            }

            user.Status = Models.UserStatus.Active;

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Enabled Account",
                Target = user.DisplayName,
                Notes = $"{user.Email} was enabled."
            });

            LoadUsersGrid();
            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{user.DisplayName}'s account has been enabled.");
        }

        // Disables the selected user account unless it is soft-deleted or already disabled.
        private void diasbleUserToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please Find and select a user first.");
                return;
            }

            if (user.Status == Models.UserStatus.SoftDeleted)
            {
                MessageBox.Show("Cannot disable a soft-deleted user. Restore the account first.");
                return;
            }

            if (user.Status == Models.UserStatus.Disabled)
            {
                MessageBox.Show($"{user.DisplayName}'s account is already disabled.");
                return;
            }

            user.Status = Models.UserStatus.Disabled;

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Disabled Account",
                Target = user.DisplayName,
                Notes = $"{user.Email} was disabled."
            });

            LoadUsersGrid();
            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{user.DisplayName}'s account has been disabled.");
        }

        // Soft-deletes the selected user after confirmation, keeping the account recoverable.
        private void softDelToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please Find and select a user first.");
                return;
            }

            if (user.Status == Models.UserStatus.SoftDeleted)
            {
                MessageBox.Show($"{user.DisplayName}'s account is already soft-deleted.");
                return;
            }

            DialogResult result = MessageBox.Show(
                $"Are you sure you want to soft-delete {user.DisplayName}?\n\n" +
                "This simulates removing the account from active use while keeping it recoverable.",
                "Confirm Soft Delete",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning
            );

            if (result != DialogResult.Yes)
                return;

            user.Status = Models.UserStatus.SoftDeleted;

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Soft Deleted Account",
                Target = user.DisplayName,
                Notes = $"{user.Email} was soft-deleted. Account is no longer active but remains recoverable."
            });

            LoadUsersGrid();
            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{user.DisplayName}'s account has been soft-deleted.");
        }

        // Restores a soft-deleted user and leaves the account disabled for review.
        private void restoreUserToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please Find and select a user first.");
                return;
            }

            if (user.Status != Models.UserStatus.SoftDeleted)
            {
                MessageBox.Show("Only soft-deleted accounts can be restored.");
                return;
            }

            user.Status = Models.UserStatus.Disabled;

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Restored Account",
                Target = user.DisplayName,
                Notes = $"{user.Email} was restored from soft-delete and set to Disabled for review."
            });

            LoadUsersGrid();
            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show(
                $"{user.DisplayName}'s account has been restored.\n\n" +
                "Status has been set to Disabled until access is reviewed."
            );
        }

        // Simulates a password reset for the selected non-soft-deleted user and records the action.
        private void resetPasswordToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please Find and select a user first.");
                return;
            }

            if (user.Status == Models.UserStatus.SoftDeleted)
            {
                MessageBox.Show("Cannot reset password for a soft-deleted user.");
                return;
            }

            string temporaryPassword = GenerateTemporaryPassword();

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Reset Password",
                Target = user.DisplayName,
                Notes = $"Temporary password issued for {user.Email}. User must change password at next sign-in."
            });

            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show(
                $"Password reset completed for {user.DisplayName}.\n\n" +
                $"Temporary Password: {temporaryPassword}\n\n" +
                "User must change password at next sign-in.",
                "Password Reset"
            );
        }

        // Assigns the selected available device to the selected user.
        private void assignDeviceToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please Find and select a user first.");
                return;
            }


            if (user.Status == Models.UserStatus.SoftDeleted)
            {
                MessageBox.Show("Cannot assign devices to a soft-deleted user. Restore the account first.");
                return;
            }

            var selectedDevice = devicesComboBox.SelectedItem as Models.Device;

            if (selectedDevice == null)
            {
                MessageBox.Show("Please Find and select a device.");
                return;
            }

            if (selectedDevice.Status == Models.DeviceStatus.Retired)
            {
                MessageBox.Show("Cannot assign a retired device. Reactivate the device first.");
                return;
            }

            if (selectedDevice.Status == Models.DeviceStatus.Lost)
            {
                MessageBox.Show("Cannot assign a lost device.");
                return;
            }

            if (selectedDevice.AssignedUserId != null && selectedDevice.AssignedUserId != user.Id)
            {
                MessageBox.Show($"{selectedDevice.DeviceName} is already assigned to another user.");
                return;
            }

            if (user.DeviceIds.Contains(selectedDevice.Id))
            {
                MessageBox.Show($"{selectedDevice.DeviceName} is already assigned to {user.DisplayName}.");
                return;
            }

            selectedDevice.AssignedUserId = user.Id;
            user.DeviceIds.Add(selectedDevice.Id);

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Assigned Device",
                Target = user.DisplayName,
                Notes = $"{selectedDevice.DeviceName} was assigned to {user.Email}."
            });

            LoadUsersGrid();
            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{selectedDevice.DeviceName} was assigned to {user.DisplayName}.");
        }

        // Retires the selected assigned device and removes it from the assigned user.
        private void retireDeviceToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var selectedDevice = GetSelectedAssignedDevice();

            if (selectedDevice == null)
            {
                MessageBox.Show("Please Find and select a device.");
                return;
            }

            var assignedUser = _store.Users
                .FirstOrDefault(user => user.Id == selectedDevice.AssignedUserId);

            DialogResult result = MessageBox.Show(
                $"Are you sure you want to retire {selectedDevice.DeviceName}?\n\n" +
                "This will remove the device from its assigned user.",
                "Confirm Device Retirement",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning
            );

            if (result != DialogResult.Yes)
                return;

            if (assignedUser != null)
            {
                assignedUser.DeviceIds.Remove(selectedDevice.Id);
            }

            selectedDevice.AssignedUserId = null;
            selectedDevice.Status = Models.DeviceStatus.Retired;

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Retired Device",
                Target = selectedDevice.DeviceName,
                Notes = assignedUser == null
                    ? $"{selectedDevice.DeviceName} was retired and was not assigned to a user."
                    : $"{selectedDevice.DeviceName} was retired and removed from {assignedUser.Email}."
            });

            LoadAuditGrid();
            LoadDevicesComboBox();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{selectedDevice.DeviceName} has been retired and unassigned.");
        }

        // Marks the selected assigned device as lost and unassigns it from the user.
        private void markDeviceAsLostToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var selectedDevice = GetSelectedAssignedDevice();

            if (selectedDevice == null)
            {
                MessageBox.Show("Please Find and select a device.");
                return;
            }

            var assignedUser = _store.Users
                .FirstOrDefault(user => user.Id == selectedDevice.AssignedUserId);

            if (assignedUser != null)
            {
                assignedUser.DeviceIds.Remove(selectedDevice.Id);
            }

            selectedDevice.AssignedUserId = null;
            selectedDevice.Status = Models.DeviceStatus.Lost;

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Marked Device Lost",
                Target = selectedDevice.DeviceName,
                Notes = assignedUser == null
                    ? $"{selectedDevice.DeviceName} was marked as lost."
                    : $"{selectedDevice.DeviceName} was marked as lost and removed from {assignedUser.Email}."
            });

            LoadAuditGrid();
            LoadDevicesComboBox();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{selectedDevice.DeviceName} has been marked as lost and unassigned.");
        }

        // Marks the selected available/inventory device as non-compliant.
        private void markNonCompliantToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var selectedDevice = devicesComboBox.SelectedItem as Models.Device;

            if (selectedDevice == null)
            {
                MessageBox.Show("Please Find and select a device.");
                return;
            }

            selectedDevice.Status = Models.DeviceStatus.NonCompliant;

            var assignedUser = _store.Users
                .FirstOrDefault(user => user.Id == selectedDevice.AssignedUserId);

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Marked Device Non-Compliant",
                Target = selectedDevice.DeviceName,
                Notes = assignedUser == null
                    ? $"{selectedDevice.DeviceName} was marked as non-compliant."
                    : $"{selectedDevice.DeviceName} assigned to {assignedUser.Email} was marked as non-compliant."
            });

            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{selectedDevice.DeviceName} has been marked as non-compliant.");
        }

        // Reactivates a retired or non-compliant available/inventory device.
        private void reactivateDeviceToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var selectedDevice = devicesComboBox.SelectedItem as Models.Device;

            if (selectedDevice == null)
            {
                MessageBox.Show("Please Find and select a device.");
                return;
            }

            if (selectedDevice.Status == Models.DeviceStatus.Active)
            {
                MessageBox.Show($"{selectedDevice.DeviceName} is already active.");
                return;
            }

            if (selectedDevice.Status == Models.DeviceStatus.Lost)
            {
                MessageBox.Show("Lost devices should not be reactivated until recovered.");
                return;
            }

            selectedDevice.Status = Models.DeviceStatus.Active;

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Reactivated Device",
                Target = selectedDevice.DeviceName,
                Notes = $"{selectedDevice.DeviceName} was reactivated and is available for assignment."
            });

            LoadAuditGrid();
            LoadDevicesComboBox();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{selectedDevice.DeviceName} has been reactivated.");
        }

        // Validates the current ticket, writes a completion audit entry, and loads the next ticket.
        private void completedTicketToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (_currentTicket == null)
            {
                MessageBox.Show("Load a ticket first.");
                return;
            }

            bool isValid = ValidateCurrentTicket(out string validationMessage);

            if (!isValid)
            {
                MessageBox.Show(
                    validationMessage,
                    "Ticket Not Complete",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Warning
                );

                return;
            }

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Completed Ticket Scenario",
                Target = _currentTicket.Title,
                Notes = _currentTicket.SuccessMessage
            });

            LoadAuditGrid();

            MessageBox.Show(
                validationMessage,
                "Ticket Completed",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information
            );
            LoadNextTicketFromQueue();
        }

        // Adds the selected user to the selected group and records the membership change.
        private void addToGroupToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please Find and select a user first.");
                return;
            }

            if (user.Status == Models.UserStatus.SoftDeleted)
            {
                MessageBox.Show("Cannot modify groups for a soft-deleted user. Restore the account first.");
                return;
            }

            var selectedGroup = groupsComboBox.SelectedItem as Models.SecurityGroup;

            if (selectedGroup == null)
            {
                MessageBox.Show("Please Find and select a group.");
                return;
            }

            if (user.GroupIds.Contains(selectedGroup.Id))
            {
                MessageBox.Show($"{user.DisplayName} is already a member of {selectedGroup.Name}.");
                return;
            }

            user.GroupIds.Add(selectedGroup.Id);
            selectedGroup.MemberUserIds.Add(user.Id);

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Added User to Group",
                Target = user.DisplayName,
                Notes = $"{user.Email} was added to {selectedGroup.Name}."
            });

            LoadUsersGrid();
            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{user.DisplayName} was added to {selectedGroup.Name}.");
        }

        // Removes the selected user from the selected group and records the membership change.
        private void removeFromGrouToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please Find and select a user first.");
                return;
            }

            if (user.Status == Models.UserStatus.SoftDeleted)
            {
                MessageBox.Show("Cannot modify groups for a soft-deleted user. Restore the account first.");
                return;
            }

            var selectedGroup = groupsComboBox.SelectedItem as Models.SecurityGroup;

            if (selectedGroup == null)
            {
                MessageBox.Show("Please Find and select a group.");
                return;
            }

            if (!user.GroupIds.Contains(selectedGroup.Id))
            {
                MessageBox.Show($"{user.DisplayName} is not a member of {selectedGroup.Name}.");
                return;
            }

            user.GroupIds.Remove(selectedGroup.Id);
            selectedGroup.MemberUserIds.Remove(user.Id);

            _store.AuditEntries.Add(new Models.AuditEntry
            {
                Actor = "Helpdesk Admin",
                Action = "Removed User from Group",
                Target = user.DisplayName,
                Notes = $"{user.Email} was removed from {selectedGroup.Name}."
            });

            LoadUsersGrid();
            LoadAuditGrid();
            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"{user.DisplayName} was removed from {selectedGroup.Name}.");
        }

        // Menu handler that opens the Add User dialog.
        private void addUserToolStripMenuItem_Click(object sender, EventArgs e)
        {
            OpenAddUserForm();
        }

        // Menu handler that opens the Add Device dialog.
        private void addDeviceToolStripMenuItem_Click(object sender, EventArgs e)
        {
            OpenAddDeviceForm();
        }

        // Menu handler that opens the Add Group dialog.
        private void createANewGroupToolStripMenuItem_Click(object sender, EventArgs e)
        {
            OpenAddGroupForm();
        }

        // Refreshes device health and ticket progress when the available-device selection changes.
        private void devicesComboBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();
        }

        // Runs user search as the search box text changes.
        private void userSearchTextBox_TextChanged(object sender, EventArgs e)
        {
            SearchUsers();
        }

        // Clears the search box, reloads all users, and selects the first visible row.
        private void clearSearchButton_Click(object sender, EventArgs e)
        {
            userSearchTextBox.Clear();

            LoadUsersGrid();
            SelectFirstUserRowIfAvailable();

        }

        // Selects the first visible user row after a search or reload while avoiding hidden grid cells.
        private void SelectFirstUserRowIfAvailable()
        {
            if (usersGridView.Rows.Count == 0)
            {
                usersGridView.ClearSelection();
                DisplaySelectedUser();
                return;
            }

            usersGridView.ClearSelection();

            var firstVisibleCell = usersGridView.Rows[0]
                .Cells
                .Cast<DataGridViewCell>()
                .FirstOrDefault(cell => cell.Visible);

            if (firstVisibleCell == null)
            {
                DisplaySelectedUser();
                return;
            }

            usersGridView.CurrentCell = firstVisibleCell;
            usersGridView.Rows[0].Selected = true;

            DisplaySelectedUser();
            UpdateTicketProgress();
        }

        // Unused Email menu click event generated by the WinForms designer.
        private void emailToolStripMenuItem_Click(object sender, EventArgs e)
        {

        }

        // Assigns a simulated mail license to the selected user.
        private void assignMailLicenseToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please find and select a user first.");
                return;
            }

            if (user.HasMailLicense)
            {
                MessageBox.Show($"{user.DisplayName} already has a mail license.");
                return;
            }

            user.HasMailLicense = true;

            AddAuditEntry(
                "Assigned Mail License",
                user.DisplayName,
                $"{user.Email} was assigned a mail license."
            );

            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"Mail license assigned to {user.DisplayName}.");
        }

        // Removes the selected user's simulated mail license and clears forwarding.
        private void removeMailLicenseToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please find and select a user first.");
                return;
            }

            if (!user.HasMailLicense)
            {
                MessageBox.Show($"{user.DisplayName} does not currently have a mail license.");
                return;
            }

            user.HasMailLicense = false;
            user.ForwardingEnabled = false;
            user.ForwardingAddress = "";

            AddAuditEntry(
                "Removed Mail License",
                user.DisplayName,
                $"{user.Email}'s mail license was removed."
            );

            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"Mail license removed from {user.DisplayName}.");
        }

        // Clears the selected user's simulated mailbox-full warning.
        private void clearMailboxFullWarningToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please find and select a user first.");
                return;
            }

            if (!user.MailboxFull)
            {
                MessageBox.Show($"{user.DisplayName}'s mailbox is not currently marked full.");
                return;
            }

            user.MailboxFull = false;

            AddAuditEntry(
                "Cleared Mailbox Full Warning",
                user.DisplayName,
                $"{user.Email}'s mailbox full warning was cleared."
            );

            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"Mailbox full warning cleared for {user.DisplayName}.");
        }

        // Enables simulated mail forwarding for the selected user using a test forwarding address.
        private void enableForwardingToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please find and select a user first.");
                return;
            }

            user.ForwardingEnabled = true;
            user.ForwardingAddress = "external.forwarding@example.com";

            AddAuditEntry(
                "Enabled Mail Forwarding",
                user.DisplayName,
                $"{user.Email}'s forwarding rule was enabled to {user.ForwardingAddress}."
            );

            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"Mail forwarding enabled for {user.DisplayName}.");
        }

        // Disables simulated mail forwarding for the selected user.
        private void disableForwardingToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please find and select a user first.");
                return;
            }

            if (!user.ForwardingEnabled)
            {
                MessageBox.Show($"{user.DisplayName} does not have forwarding enabled.");
                return;
            }

            string oldForwardingAddress = user.ForwardingAddress;

            user.ForwardingEnabled = false;
            user.ForwardingAddress = "";

            AddAuditEntry(
                "Disabled Mail Forwarding",
                user.DisplayName,
                $"{user.Email}'s forwarding rule to {oldForwardingAddress} was disabled."
            );

            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"Mail forwarding disabled for {user.DisplayName}.");
        }

        // Blocks the selected user's simulated mailbox.
        private void blockMailboxToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please find and select a user first.");
                return;
            }

            if (user.MailboxBlocked)
            {
                MessageBox.Show($"{user.DisplayName}'s mailbox is already blocked.");
                return;
            }

            user.MailboxBlocked = true;

            AddAuditEntry(
                "Blocked Mailbox",
                user.DisplayName,
                $"{user.Email}'s mailbox was blocked."
            );

            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"Mailbox blocked for {user.DisplayName}.");
        }

        // Unblocks the selected user's simulated mailbox.
        private void unblockMailboxToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var user = GetSelectedUser();

            if (user == null)
            {
                MessageBox.Show("Please find and select a user first.");
                return;
            }

            if (!user.MailboxBlocked)
            {
                MessageBox.Show($"{user.DisplayName}'s mailbox is not blocked.");
                return;
            }

            user.MailboxBlocked = false;

            AddAuditEntry(
                "Unblocked Mailbox",
                user.DisplayName,
                $"{user.Email}'s mailbox was unblocked."
            );

            DisplaySelectedUser();
            UpdateTicketProgress();

            MessageBox.Show($"Mailbox unblocked for {user.DisplayName}.");
        }

        // Simulates applying Windows updates to the selected device.
        private void runWindowsUpdateToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                MessageBox.Show("Please select a device first.");
                return;
            }

            if (!device.WindowsUpdatePending)
            {
                MessageBox.Show($"{device.DeviceName} has no pending Windows updates.");
                return;
            }

            device.WindowsUpdatePending = false;

            AddAuditEntry(
                "Ran Windows Update",
                device.DeviceName,
                $"{device.DeviceName} Windows updates were applied."
            );

            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();

            MessageBox.Show($"Windows updates completed for {device.DeviceName}.");
        }

        // Enables BitLocker on the selected device.
        private void enableBitlockerToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                MessageBox.Show("Please select a device first.");
                return;
            }

            if (device.BitLockerEnabled)
            {
                MessageBox.Show($"{device.DeviceName} already has BitLocker enabled.");
                return;
            }

            device.BitLockerEnabled = true;

            AddAuditEntry(
                "Enabled BitLocker",
                device.DeviceName,
                $"{device.DeviceName} BitLocker was enabled."
            );

            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();

            MessageBox.Show($"BitLocker enabled for {device.DeviceName}.");
        }

        // Disables BitLocker on the selected device for testing scenarios.
        private void disableBitlockerToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                MessageBox.Show("Please select a device first.");
                return;
            }

            if (device.DefenderEnabled)
            {
                MessageBox.Show($"{device.DeviceName} already has Defender enabled.");
                return;
            }

            device.DefenderEnabled = true;

            AddAuditEntry(
                "Enabled Defender",
                device.DeviceName,
                $"{device.DeviceName} Microsoft Defender was enabled."
            );

            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();

            MessageBox.Show($"Microsoft Defender enabled for {device.DeviceName}.");
        }

        // Simulates disk cleanup on the selected device.
        private void clearDiskSpaceToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                MessageBox.Show("Please select a device first.");
                return;
            }

            if (device.DiskSpaceFreePercent >= 15)
            {
                MessageBox.Show($"{device.DeviceName} does not have low disk space.");
                return;
            }

            device.DiskSpaceFreePercent = 35;

            AddAuditEntry(
                "Cleared Disk Space",
                device.DeviceName,
                $"{device.DeviceName} disk cleanup was completed. Free space is now {device.DiskSpaceFreePercent}%."
            );

            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();

            MessageBox.Show($"Disk cleanup completed for {device.DeviceName}.");
        }

        // Refreshes the selected device's check-in age.
        private void refreshDeviceCheckInToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                MessageBox.Show("Please select a device first.");
                return;
            }

            device.DaysSinceLastCheckIn = 0;

            AddAuditEntry(
                "Refreshed Device Check-In",
                device.DeviceName,
                $"{device.DeviceName} check-in was refreshed."
            );

            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();

            MessageBox.Show($"{device.DeviceName} check-in refreshed.");
        }

        // Grants simulated temporary local admin on the selected device.
        private void grantTemporaryLocalADminToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                MessageBox.Show("Please select a device first.");
                return;
            }

            if (device.LocalAdminGranted)
            {
                MessageBox.Show($"{device.DeviceName} already has temporary local admin granted.");
                return;
            }

            device.LocalAdminGranted = true;

            AddAuditEntry(
                "Granted Temporary Local Admin",
                device.DeviceName,
                $"{device.DeviceName} was granted temporary local admin access."
            );

            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();

            MessageBox.Show($"Temporary local admin granted for {device.DeviceName}.");
        }

        // Removes simulated local admin from the selected device.
        private void removeLocalAdminToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                MessageBox.Show("Please select a device first.");
                return;
            }

            if (!device.LocalAdminGranted)
            {
                MessageBox.Show($"{device.DeviceName} does not currently have temporary local admin granted.");
                return;
            }

            device.LocalAdminGranted = false;

            AddAuditEntry(
                "Removed Local Admin",
                device.DeviceName,
                $"{device.DeviceName} temporary local admin access was removed."
            );

            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();

            MessageBox.Show($"Temporary local admin removed from {device.DeviceName}.");
        }

        // Marks the selected device compliant/active after review.
        private void markDeviceCompliantToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var device = GetSelectedDevice();

            if (device == null)
            {
                MessageBox.Show("Please select a device first.");
                return;
            }

            device.Status = Models.DeviceStatus.Active;

            AddAuditEntry(
                "Marked Device Compliant",
                device.DeviceName,
                $"{device.DeviceName} was marked compliant after review."
            );

            LoadDevicesComboBox();
            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();

            MessageBox.Show($"{device.DeviceName} marked compliant.");
        }

        // Refreshes device health and ticket progress when an assigned device is selected.
        private void userDevicesListBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            DisplaySelectedDeviceHealth();
            UpdateTicketProgress();
        }

        // Menu handler that skips the current ticket.
        private void sKipTicketToolStripMenuItem_Click(object sender, EventArgs e)
        {
            SkipCurrentTicket();
        }
        // Confirms skipping, writes an audit entry, clears the current ticket, and loads the next one.
        private void SkipCurrentTicket()
        {
            if (_currentTicket == null)
            {
                MessageBox.Show("No ticket is currently loaded.");
                return;
            }

            DialogResult result = MessageBox.Show(
                $"Skip this ticket?\n\n{_currentTicket.Title}",
                "Skip Ticket",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Question
            );

            if (result != DialogResult.Yes)
                return;

            AddAuditEntry(
                "Skipped Ticket Scenario",
                _currentTicket.Title,
                "Ticket was skipped by the trainee."
            );

            _currentTicket = null;
            _currentTicketReadyToComplete = false;

            expectedActionsCheckedListBox.Items.Clear();

            LoadNextTicketFromQueue();
        }
    }
}
